feat: support additionalParams on HTTP-POST binding
node-saml/node-saml pull request #263
Opened 2023-04-05 15:18 UTC by GertSallaerts

# Description

This allows consumers of the library to include the `additionalParams` in options when working with `getAuthorizeFormAsync` like you can also do with `getAuthorizeUrlAsync`. It would, for example, allow overriding RelayState in `passport-saml` or adding any arbitrary additional parameters your SAML integration may require.

# Checklist:

- Issue Addressed: [x]
- Link to SAML spec: [N/A]
- Tests included? [x]
- Documentation updated? [N/A (I think?)]

2023-04-12 21:00 UTC, cjbarth commented on test/samlRequest.spec.ts
> +  it.only("With additional run-time parameters", async function () {
Why the `.only()`?

2023-04-14 13:24 UTC, GertSallaerts commented on test/samlRequest.spec.ts
> +  it.only("With additional run-time parameters", async function () {
An oversight, fixed!

2023-04-15 22:14 UTC, cjbarth commented
@GertSallaerts , before I review this, can you please merge `master` into this branch?

2023-04-15 22:15 UTC, cjbarth requested changes
Please merge `master` into this branch.

2023-04-15 23:05 UTC, cjbarth commented
BTW, I'm going to try to work with you to get this landed before I start work on the 5.x branch which will release soon to support the next version of Node.

2023-04-17 06:26 UTC, GertSallaerts commented
> Please merge `master` into this branch.

Rebased on master @cjbarth 

> BTW, I'm going to try to work with you to get this landed before I start work on the 5.x branch which will release soon to support the next version of Node.

Thanks!

2023-04-18 12:26 UTC, cjbarth approved these changes

2023-04-18 13:58 UTC, cjbarth commented
Do you think you can add a test that fixes the codecov error?

2023-04-19 13:46 UTC, GertSallaerts commented
@cjbarth added a test that makes sure 100% of my changes are covered by tests (I think, not sure if I can confirm it on local dev?) It seemed like a very silly test so please let me know if that isn't what you meant.

2023-04-20 15:27 UTC, cjbarth approved these changes

2023-04-20 15:27 UTC, merged

2023-04-20 15:31 UTC, cjbarth commented
The test is valuable because it supports backwards compatibility with those that aren't using this feature :)

2023-05-22 09:06 UTC, GertSallaerts commented
Do you have plans to release this in the near future (and do those plans include inclusion in a release of passport-saml as well)?